Speed improvements
LCAV/pylocus pull request #18
Opened 2018-04-23 18:28 UTC by oleksandr-pavlyk

I just stumbled into this project, and notices that functions in `basics` could be sped-up a bit with more efficient use of NumPy. For example `mse` on vectors is 9X faster, and 5X faster on matrices.

Also sped-up code in MDS.

Please let me know what you think

2018-04-30 17:41 UTC, oleksandr-pavlyk commented
ping.

2018-05-02 04:09 UTC, duembgen commented
Hi thank you very much for the contribution! I am reviewing it now, will get back asap

2018-05-02 04:40 UTC, duembgen commented
Very valuable contribution, learned a few tricks while reading this! If you could just remove the few lines of code that you commented out to replace them with something more efficient, that'd be great. I added notes for the two places where the comments should be left. 

Also sorry for the late answer, I was not notified about this pull request (thank you @fakufaku for the notice).

2018-05-02 04:41 UTC, duembgen requested changes

2018-05-02 04:41 UTC, duembgen commented on pylocus/basics.py
> +    # N.B.:
good point. All above "N.B.:" can be deleted

2018-05-02 04:41 UTC, duembgen commented on pylocus/basics.py
> +    #G_hat = np.dot(np.dot(u, np.diag(lamda)), u.T)
leave this comment (for later testing)

2018-05-02 04:41 UTC, duembgen commented on pylocus/mds.py
> +        return x_from_eigendecomp(factor, u, dim)
nice find, didn't notice this ugly duplicate code.

2018-05-07 06:43 UTC, duembgen approved these changes

2018-05-07 06:44 UTC, merged

2018-05-07 06:45 UTC, duembgen commented
Thank you for the contrubution, oleksandr-pavlyk. Chamges are now merged